name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
    - run: |
        sudo apt update && sudo apt upgrade -y && sudo apt install libturbojpeg-dev libavif-dev openslide-tools -y
    - name: configure
      run: |
        cmake -B build -DIRIS_BUILD_PYTHON=ON
    - name: make
      run: | 
        cmake --build build --config Release
        
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
