name: Distribute Python Artifacts to PyPi

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_python_module:
    runs-on: ${{ matrix.os }}
    permissions:
        id-token: write
    strategy: 
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-13, windows-latest]
    steps:
          - uses: actions/checkout@v4
          - uses: ilammy/setup-nasm@v1
          - uses: actions/setup-python@v5
            with:
                python-version: '3.13' 

          - name: Update Pip
            run: |
                python -m pip install --upgrade pip 
                pip install build scikit-build-core
          - name: Build Self-contained Python Module
            run: |
                python -m build ${{ github.workspace }} --wheel

          - name: Upload Build Artifact
            uses: actions/upload-artifact@v4
            with:
                name: ${{ matrix.os }}
                path: ${{ github.workspace }}/dist/

          - name: Publish to PyPi 
            uses: pypa/gh-action-pypi-publish@release/v1
            with:
                repository-url: https://test.pypi.org/legacy/
